CREATE TABLE RILCA.STAFF(
Fname varchar(50),
Lname varchar(50),
Staff_ID varchar(10),
Address varchar(120),
Phone_no INT(6),
Date_joined DATE,
Program_ID varchar(50),
PRIMARY KEY (Staff_ID)
);

CREATE TABLE RILCA.EXECUTIVE (	
Exec_ID varchar(10),
PRIMARY KEY(Exec_ID),
FOREIGN KEY (Exec_ID) REFERENCES RILCA.STAFF(Staff_ID));

CREATE TABLE RILCA.DIRECTOR (
Dir_ID varchar(10),
PRIMARY KEY(Dir_ID),
FOREIGN KEY (Dir_ID) REFERENCES EXECUTIVE(Exec_ID));

CREATE TABLE RILCA.DEPUTY_DIR (	
DeputyDir_ID varchar(10),
PRIMARY KEY(DeputyDir_ID),
FOREIGN KEY (DeputyDir_ID) REFERENCES EXECUTIVE(Exec_ID));

CREATE TABLE RILCA.ACADEMIC_STAFF (
Ac_ID varchar(10),
Title VARCHAR(25),
PRIMARY KEY(Ac_ID),
FOREIGN KEY (Ac_ID) REFERENCES STAFF(Staff_ID));

CREATE TABLE RILCA.SUPPORTIVE_STAFF (
S_ID varchar(10),
S_Title VARCHAR(25),
PRIMARY KEY(S_ID),
FOREIGN KEY (S_ID) REFERENCES STAFF(Staff_ID));

CREATE TABLE RILCA.PA_ITEM (
Item_ID INT(5),
Parent_id INT(5),
G_Desc_eng VARCHAR(100),
G_Desc_thai VARCHAR(100),
PRIMARY KEY (Item_ID),
FOREIGN KEY (Parent_id) REFERENCES RILCA.PA_ITEM(Item_ID));

CREATE TABLE RILCA.PA_DOCUMENT (
Doc_ID VARCHAR(10),
Doc_year VARCHAR(5),
Doc_Status VARCHAR(20),
DirSign_Date DATE,
DDirSign_Date DATE,
Approve_Date DATE,
Set_date DATE,
Accept_date DATE,
SignDir_ID VARCHAR(10),
SignDDir_ID VARCHAR(10),
PAExec_ID VARCHAR(10),
Acad_ID VARCHAR(10),
PRIMARY KEY (Doc_ID),
FOREIGN KEY (SignDir_ID) REFERENCES RILCA.DIRECTOR(Dir_ID),
FOREIGN KEY (SignDDir_ID) REFERENCES RILCA.DEPUTY_DIR(DeputyDir_ID),
FOREIGN KEY (PAExec_ID) REFERENCES RILCA.EXECUTIVE(Exec_ID),
FOREIGN KEY (Acad_ID) REFERENCES RILCA.ACADEMIC_STAFF(Ac_ID));

CREATE TABLE RILCA.PA_LINE (
PAline_Score int(5),
PADoc_ID VARCHAR(10),
PAitem_ID INT(5),
SS_ID VARCHAR(10),
upsert_date DATE,
FOREIGN KEY (PADoc_ID) REFERENCES PA_DOCUMENT(Doc_ID),
FOREIGN KEY (PAitem_ID) REFERENCES PA_ITEM(Item_ID),
FOREIGN KEY (SS_ID) REFERENCES RILCA.SUPPORTIVE_STAFF(S_ID));